name: Deploy to Maven Central

on:
  push:
    branches:
      - main  # Trigger deployment only on the main branch

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: macos-latest  # Use macOS for iOS builds
    env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Step 3: Build Artifacts
      - name: Build Artifacts And Publish
        run: |
          ./gradlew buildAllPlatformsAndPublish --info --stacktrace --scan -Dorg.gradle.internal.http.debug=true

      - name: Upload Problems Report
        if: failure() # Only upload if the build fails
        uses: actions/upload-artifact@v3
        with:
          name: problems-report
          path: build/reports/problems/problems-report.html