name: Deploy to Maven Central

on:
  push:
    branches:
      - main  # Trigger deployment only on the main branch

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: macos-latest  # Use macOS for iOS builds
    env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Set up Xcode
      - name: Install Xcode Command Line Tools
        run: |
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      # Step 4: Publish to Maven Central
      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache --info --stacktrace