name: Deploy to Maven Central

on:
  push:
    branches:
      - main  # Trigger deployment only on the main branch

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Debug secrets
        run: |
          if [ -z "${{ secrets.GPG_PRIVATE_KEY }}" ]; then
            echo "GPG_PRIVATE_KEY is NOT set or is empty."
          else
            echo "GPG_PRIVATE_KEY is set."
          fi

          if [ -z "${{ secrets.GPG_PASSPHRASE }}" ]; then
            echo "GPG_PASSPHRASE is NOT set or is empty."
          else
            echo "GPG_PASSPHRASE is set."
          fi

          if [ -z "${{ secrets.OSSRH_USERNAME }}" ]; then
            echo "OSSRH_USERNAME is NOT set or is empty."
          else
            echo "OSSRH_USERNAME is set."
          fi

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          gpg --list-keys
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>ossrh</id>
                      <username>${{ secrets.OSSRH_USERNAME }}</username>
                      <password>${{ secrets.OSSRH_PASSWORD }}</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      - name: Build and publish
        run: ./gradlew clean publish --no-configuration-cache -Psigning.gnupg.keyName="${{ secrets.GPG_KEY_ID }}" -Psigning.gnupg.passphrase="${{ secrets.GPG_PASSPHRASE }}"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
